import type { ThemePreset } from "./registry.ts";
import { buildFontStack, hexToRgb, mixHex, normalizeHex, rgbString, rgbToHsl } from "./utils.ts";

const colorVarNameByToken: Record<keyof ThemePreset["tokens"], string> = {
  canvas: "--theme-canvas",
  surface: "--theme-surface",
  surfaceAlt: "--theme-surface-alt",
  surfaceStrong: "--theme-surface-strong",
  textPrimary: "--theme-text-primary",
  textMuted: "--theme-text-muted",
  textInverse: "--theme-text-inverse",
  border: "--theme-border",
  borderStrong: "--theme-border-strong",
  primary: "--theme-primary",
  primaryForeground: "--theme-primary-foreground",
  accent: "--theme-accent",
  accentForeground: "--theme-accent-foreground",
  success: "--theme-success",
  successForeground: "--theme-success-foreground",
  danger: "--theme-danger",
  dangerForeground: "--theme-danger-foreground",
  navSolidBg: "--theme-nav-solid-bg",
  navSolidFg: "--theme-nav-solid-fg",
  navSolidInteractive: "--theme-nav-solid-interactive",
  focusRing: "--theme-focus-ring",
  shadowSoft: "--theme-shadow-soft",
};

const buttonVarNameByToken: Record<keyof ThemePreset["components"]["button"], string> = {
  primaryBg: "--theme-button-primary-bg",
  primaryFg: "--theme-button-primary-fg",
  primaryHoverBg: "--theme-button-primary-hover-bg",
  secondaryBg: "--theme-button-secondary-bg",
  secondaryFg: "--theme-button-secondary-fg",
  secondaryHoverBg: "--theme-button-secondary-hover-bg",
  outlineBg: "--theme-button-outline-bg",
  outlineFg: "--theme-button-outline-fg",
  outlineBorder: "--theme-button-outline-border",
  outlineHoverBg: "--theme-button-outline-hover-bg",
  outlineHoverFg: "--theme-button-outline-hover-fg",
  ghostFg: "--theme-button-ghost-fg",
  ghostHoverBg: "--theme-button-ghost-hover-bg",
  ghostHoverFg: "--theme-button-ghost-hover-fg",
  destructiveBg: "--theme-button-destructive-bg",
  destructiveFg: "--theme-button-destructive-fg",
  destructiveHoverBg: "--theme-button-destructive-hover-bg",
  linkFg: "--theme-button-link-fg",
  linkHoverFg: "--theme-button-link-hover-fg",
};

export const compileThemeVars = (preset: ThemePreset): Record<string, string> => {
  const mutedSoft = mixHex(preset.tokens.textMuted, preset.tokens.canvas, 0.35);

  return {
    ...Object.fromEntries(
      Object.entries(preset.tokens).map(([tokenName, value]) => [colorVarNameByToken[tokenName as keyof ThemePreset["tokens"]], value]),
    ),
    ...Object.fromEntries(
      Object.entries(preset.components.button).map(([tokenName, value]) => [
        buttonVarNameByToken[tokenName as keyof ThemePreset["components"]["button"]],
        value,
      ]),
    ),
    "--theme-heading-font": buildFontStack(preset.typography.headingFamily, preset.typography.headingFallback),
    "--theme-body-font": buildFontStack(preset.typography.bodyFamily, preset.typography.bodyFallback),
    "--theme-radius-sm": preset.radius.sm,
    "--theme-radius-md": preset.radius.md,
    "--theme-radius-lg": preset.radius.lg,
    "--theme-radius-pill": preset.radius.pill,
    "--shadow-soft": preset.tokens.shadowSoft,
    "--font-heading": buildFontStack(preset.typography.headingFamily, preset.typography.headingFallback),
    "--font-body": buildFontStack(preset.typography.bodyFamily, preset.typography.bodyFallback),
    "--font-display": buildFontStack(preset.typography.headingFamily, preset.typography.headingFallback),
    "--border-radius": preset.radius.md,
    "--radius": preset.radius.md,
    "--color-primary": normalizeHex(preset.tokens.primary),
    "--color-secondary": normalizeHex(preset.tokens.surface),
    "--color-accent": normalizeHex(preset.tokens.accent),
    "--color-navbar-solid": normalizeHex(preset.tokens.navSolidBg),
    "--color-navbar-solid-foreground": normalizeHex(preset.tokens.navSolidFg),
    "--color-navbar-solid-interactive": normalizeHex(preset.tokens.navSolidInteractive),
    "--color-muted": normalizeHex(preset.tokens.textMuted),
    "--color-muted-soft": mutedSoft,
    "--color-border": normalizeHex(preset.tokens.border),
    "--color-surface": normalizeHex(preset.tokens.surface),
    "--color-surface-alt": normalizeHex(preset.tokens.surfaceAlt),
    "--color-surface-strong": normalizeHex(preset.tokens.surfaceStrong),
    "--color-danger": normalizeHex(preset.tokens.danger),
    "--color-success": normalizeHex(preset.tokens.success),
    "--color-primary-rgb": rgbString(preset.tokens.primary),
    "--color-secondary-rgb": rgbString(preset.tokens.surface),
    "--color-accent-rgb": rgbString(preset.tokens.accent),
    "--color-navbar-solid-rgb": rgbString(preset.tokens.navSolidBg),
    "--color-navbar-solid-foreground-rgb": rgbString(preset.tokens.navSolidFg),
    "--color-navbar-solid-interactive-rgb": rgbString(preset.tokens.navSolidInteractive),
    "--color-danger-rgb": rgbString(preset.tokens.danger),
    "--color-success-rgb": rgbString(preset.tokens.success),
    "--background": rgbToHsl(hexToRgb(preset.tokens.canvas)),
    "--foreground": rgbToHsl(hexToRgb(preset.tokens.textPrimary)),
    "--card": rgbToHsl(hexToRgb(preset.tokens.surface)),
    "--card-foreground": rgbToHsl(hexToRgb(preset.tokens.textPrimary)),
    "--popover": rgbToHsl(hexToRgb(preset.tokens.surface)),
    "--popover-foreground": rgbToHsl(hexToRgb(preset.tokens.textPrimary)),
    "--primary": rgbToHsl(hexToRgb(preset.tokens.primary)),
    "--primary-foreground": rgbToHsl(hexToRgb(preset.tokens.primaryForeground)),
    "--secondary": rgbToHsl(hexToRgb(preset.tokens.surfaceAlt)),
    "--secondary-foreground": rgbToHsl(hexToRgb(preset.tokens.textPrimary)),
    "--muted": rgbToHsl(hexToRgb(preset.tokens.surfaceAlt)),
    "--muted-foreground": rgbToHsl(hexToRgb(preset.tokens.textMuted)),
    "--accent": rgbToHsl(hexToRgb(preset.tokens.accent)),
    "--accent-foreground": rgbToHsl(hexToRgb(preset.tokens.accentForeground)),
    "--destructive": rgbToHsl(hexToRgb(preset.tokens.danger)),
    "--destructive-foreground": rgbToHsl(hexToRgb(preset.tokens.dangerForeground)),
    "--border": rgbToHsl(hexToRgb(preset.tokens.border)),
    "--input": rgbToHsl(hexToRgb(preset.tokens.border)),
    "--ring": rgbToHsl(hexToRgb(preset.tokens.focusRing)),
  };
};
