import type { ThemePreset } from "../registry.ts";

export const heritageThemePreset: ThemePreset = {
  key: "heritage",
  label: "Heritage Editorial",
  description: "Forest greens, warm ivory, and gold accents shaped for an editorial print house.",
  tokens: {
    canvas: "#FCF9F5",
    surface: "#FFFFFF",
    surfaceAlt: "#F6F3EF",
    surfaceStrong: "#F0EDEA",
    textPrimary: "#1C1C1A",
    textMuted: "#71695E",
    textInverse: "#FFFFFF",
    border: "#E2DCCF",
    borderStrong: "#CDBEAA",
    primary: "#001B0F",
    primaryForeground: "#FFFFFF",
    accent: "#735C00",
    accentForeground: "#FFFFFF",
    success: "#2F6B4F",
    successForeground: "#FFFFFF",
    danger: "#A13F32",
    dangerForeground: "#FFFFFF",
    navSolidBg: "#FCF9F5",
    navSolidFg: "#001B0F",
    navSolidInteractive: "#735C00",
    focusRing: "#735C00",
    shadowSoft: "0 20px 60px rgba(28, 28, 26, 0.08)",
  },
  components: {
    button: {
      primaryBg: "#735C00",
      primaryFg: "#FFFFFF",
      primaryHoverBg: "#8A6E00",
      secondaryBg: "#013220",
      secondaryFg: "#FFFFFF",
      secondaryHoverBg: "#001B0F",
      outlineBg: "#FFFFFF",
      outlineFg: "#001B0F",
      outlineBorder: "#E2DCCF",
      outlineHoverBg: "#F0EDEA",
      outlineHoverFg: "#001B0F",
      ghostFg: "#001B0F",
      ghostHoverBg: "#F6F3EF",
      ghostHoverFg: "#735C00",
      destructiveBg: "#A13F32",
      destructiveFg: "#FFFFFF",
      destructiveHoverBg: "#873327",
      linkFg: "#001B0F",
      linkHoverFg: "#735C00",
    },
  },
  typography: {
    headingFamily: "Noto Serif",
    bodyFamily: "Inter",
    headingFallback: "Georgia, serif",
    bodyFallback: "system-ui, sans-serif",
  },
  radius: {
    sm: "0.125rem",
    md: "0.25rem",
    lg: "0.5rem",
    pill: "9999px",
  },
};
